version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8 # Specify the Python version you want to use
    commands:
      - echo "Installing dependencies..."
      # Uncomment the following line if you have a requirements.txt file
      # - pip install -r requirements.txt
  build:
    commands:
      - echo "Build started on $(date)"
      - python hello-world.py # Run the Python script
  post_build:
    commands:
      - echo "Build completed on $(date)"
      - echo "Hello World! Build completed successfully."

